- src/about/index.jade
- src/docs/billing.jade
- src/docs/index.jade
- src/docs/retail.jade
- src/docs/settlement.jade
- src/features.jade
- src/tour.jade
> Language Changes for About, Settlement, Tour, Docs 

- src/docs/billing.jade
- src/docs/donations.jade
- src/docs/ecommerce.jade
- src/docs/index.jade
- src/docs/retail.jade
- src/docs/settlement.jade
- src/integrations.jade
Review and merge when ready, @bitjson
> Touching up language on Docs and Integrations, adding links and CTA's to Docs pages. 

- src/about/team.jade
- src/docs/billing.jade
- src/docs/donations.jade
- src/docs/ecommerce.jade
- src/docs/index.jade
- src/docs/retail.jade
> Fix links on Docs

- src/integrations.jade
> Add instruction guide links to integration page icons

- src/about/index.jade
Small change to fix typo on Bryan's bio. @bitjson
> Remove about page bio typo

- src/about/team.jade
- src/features.jade
@bitjson, Elyse spotted an incomplete sentence/typo on our features page which should be corrected.
> fix typo on support features

- src/docs/retail.jade
> Add POS Integration Instructions

- src/about/index.jade
@bitjson Changed Tony's title from "Chairman of the Board" to "Executive Chairman." Per Stephen's request, modified "CEO" to "Chief Executive Officer" to match format of other executive titles.
> Correct Executive Titles

- src/about/index.jade
@bitjson good to go CC: @pat-riley
> Add Marcel Roelants to About Page

- src/integrations/index.jade
- src/integrations/xcart.jade
- src/integrations/zen-cart.jade
> Add Zen Cart and X-Cart Pages

- src/integrations/drupal-commerce.jade
> Add Drupal Commerce Page

- src/_layouts/docs.jade
- src/docs/testing.jade
@bitjson This is a work in progress. Not ready for merge – pull request is in review.
> Add Testing Documentation Page

- src/integrations/drupal-commerce.jade
- src/integrations/index.jade
- src/integrations/magento.jade
- src/integrations/opencart.jade
- src/integrations/oscommerce.jade
- src/integrations/prestashop.jade
- src/integrations/shopify.jade
- src/integrations/virtuemart.jade
- src/integrations/woocommerce.jade
- src/integrations/wordpress.jade
- src/integrations/xcart.jade
- src/integrations/zen-cart.jade
- src/pricing.jade
all related to integrations pages
> Corrected GH links, formatting and QB name

- src/pricing.jade
> Fix Duplicate

- src/docs/settlement.jade
> Settlement Updates

- src/about/press.jade
> Remove Phone Number

- src/docs/settlement.jade
@bitjson Updates settlement page to reflect new minimum.
> MXN Settlement Minimum Update

- src/integrations/index.jade
> changed sizes of integration logos

- src/_includes/footer.jade
> HTTPS All the Links

- src/integrations/ingenico.jade
> Fix YouTube Link on Ingenico Page

- src/enterprise.jade
> Update Settlement Info on Enterprise Page

- src/_includes/integration-dropdown.jade
- src/_scripts/init.js
Fix https://github.com/bitpay/bitpay-website/issues/128
> Move inline event handler to init script

- src/docs/settlement.jade
> GBP Settlement Minimum
